# Generated by Django 6.0.4 on 2026-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_sitesetting_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional course notes or resources', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to course video (e.g. YouTube, Vimeo)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
