# Generated by Django 6.0.4 on 2026-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_notes_course_video_url_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notes_pdf',
            field=models.FileField(blank=True, help_text='Upload notes as PDF', null=True, upload_to='course_notes/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional course notes or resources (text)', null=True),
        ),
    ]
